### ISSUE TITLE
A lot of strings in Weblate are marked as “read-only”

### ISSUE THREAD

**Issue by fitojb** [lduboeuf/Stellarium-mobile#18]
which impedes its editing. Many of these strings in Spanish contain numerous errors :(

**Comment by lduboeuf** [comment]
yes it seems that there is an issue with weblate but don't know what to do

**Comment by fitojb** [comment]
@lduboeuf Do you accept pull requests?

**Comment by lduboeuf** [comment]
of course

**Comment by lduboeuf** [comment]
can you confirm it is fixed ?

**Comment by fitojb** [comment]
Yes, it is! Thank you very much!!
