### ISSUE TITLE
app crashes when started in landscape mode

### ISSUE THREAD

**Issue by Danfro** [lduboeuf/Stellarium-mobile#2]
When starting the app in portrait mode it works fine. After it has opened I can change to landscape mode.

But if I try to open the app in landscape mode it crashes/does not start. The splash screen is shown, then the window closes.

This is running E5 on edge.

**Comment by tux4us** [comment]
Also on M10FHD edge

**Comment by lduboeuf** [comment]
confirmed on N5 also. was it the case on stable or devel ?

**Comment by Danfro** [comment]
I am afraid I don't know if that is the case on stable or RC or devel too.

**Comment by StefWe** [comment]
On stable with mx4 it works like expected, no crash.

**Comment by lduboeuf** [comment]
could be related to Mir/Unity8 so, i fill a bug

**Comment by lduboeuf** [comment]
refs: https://github.com/ubports/ubuntu-touch/issues/1241
